name: emtc_app
description: e-MTC TC - Electronic Market for Textiles and Clothing (TC, GoI) - Mobile app for Liaison Officers to collect survey data
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Location services
  location: ^6.0.0
  
  # Connectivity monitoring
  connectivity_plus: ^5.0.2
  
  # HTTP requests
  http: ^1.1.0
  
  # Crypto and security
  crypto: ^3.0.3
  encrypt: ^5.0.3
  
  # UI components
  signature: ^5.4.0
  
  # State management
  provider: ^6.1.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Charts
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 